# Generated by Django 4.2.5 on 2023-09-09 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Uploader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Completed'), (1, 'Uploading')])),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField()),
                ('size', models.BigIntegerField()),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
    ]
