# Generated by Django 4.2.5 on 2023-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3uploader',
            name='size',
            field=models.BigIntegerField(default=-1),
        ),
    ]
