services:
  app:
    build:
      context: .
    env_file:
      - .env

  pg:
    image: postgres:15
    env_file:
      - .env

  minio:
    image: minio/minio
    env_file:
      - .env
    command: server /data --console-address ':9001'
