# Generated by Django 4.2.5 on 2023-09-23 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
