# Generated by Django 4.2.5 on 2023-09-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_comment_key_alter_ticket_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_modified',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_updated',
        ),
    ]
