# Generated by Django 4.2.7 on 2023-11-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_manager_name': 'objects'},
        ),
    ]
