# Generated by Django 4.2.5 on 2023-09-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_s3uploader_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3uploader',
            name='username',
            field=models.CharField(default='shimon', max_length=150),
            preserve_default=False,
        ),
    ]
