# Generated by Django 4.2.5 on 2023-09-23 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_s3uploader_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='s3uploader',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
