# Generated by Django 4.2.5 on 2023-10-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_remove_uploadedfile_id_alter_s3uploader_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='username',
            field=models.CharField(default='shimon', max_length=150),
            preserve_default=False,
        ),
    ]
