# Generated by Django 4.2.6 on 2023-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_uploadedfile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3uploader',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
