# Generated by Django 4.2.7 on 2023-11-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_s3uploader_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3uploader',
            old_name='id',
            new_name='key',
        ),
    ]
