# Generated by Django 4.2.7 on 2023-11-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_alter_uploadedfile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3uploader',
            options={'default_manager_name': 'objects'},
        ),
    ]
