# Generated by Django 4.2.7 on 2023-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_s3uploader_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3uploader',
            name='size',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
